name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag discord-minecraft-bot:$(date +%s)
        docker tag discord-minecraft-bot:$(date +%s) discord-minecraft-bot:latest
